=== jovanf1/PrviProjekat/Oglasi.dtd
<!ELEMENT Oglasi (Oglas+)>
<!ELEMENT Oglas (Kategorija, DatumIsteka, Cena, Tekst, Tag+, Email)>

<!ELEMENT Kategorija (#PCDATA)>
<!ELEMENT DatumIsteka (Dan, Mesec, Godina)>
<!ELEMENT Dan (#PCDATA)>
<!ELEMENT Mesec (#PCDATA)>
<!ELEMENT Godina (#PCDATA)>
<!ELEMENT Cena (Iznos)>
<!ELEMENT Iznos (#PCDATA)>
<!ELEMENT Tekst (#PCDATA)>
<!ELEMENT Tag (#PCDATA)>
<!ELEMENT Email (#PCDATA)>

<!ATTLIST Oglas id CDATA #REQUIRED>
<!ATTLIST Kategorija tip (automobili|stanovi|alati|podučavanje) #REQUIRED>
<!ATTLIST Cena valuta (din|eur) "din">
<!ATTLIST Email tip (privatni|sluzbeni) #REQUIRED>

=== jovanf1/PrviProjekat/Oglasi.xml
<?xml version="1.0" encoding="utf-8" standalone="no"?>
<!DOCTYPE Oglasi SYSTEM "Oglasi.dtd">
<?xml-stylesheet type ="text/xsl" href ="Oglasi.xslt"?>
<Oglasi>
  <Oglas id="0">
    <Kategorija tip="automobili"></Kategorija>
    <DatumIsteka>
      <Dan></Dan>
      <Mesec></Mesec>
      <Godina></Godina>
    </DatumIsteka>
    <Cena valuta="din">
      <Iznos>1200</Iznos>
    </Cena>
    <Tekst></Tekst>
    <Tag></Tag>
    <Email tip="privatni"></Email>
  </Oglas>
  <Oglas id="1">
    <Kategorija tip="automobili"></Kategorija>
    <DatumIsteka>
      <Dan></Dan>
      <Mesec></Mesec>
      <Godina></Godina>
    </DatumIsteka>
    <Cena valuta="eur">
      <Iznos>890</Iznos>
    </Cena>
    <Tekst></Tekst>
    <Tag></Tag>
    <Email tip="sluzbeni"></Email>
  </Oglas>
</Oglasi>
